services:
  main:
    build:
      context: ..
      dockerfile: src/Dockerfile
    tty: true
    stdin_open: true
    init: true
  test:
    build:
      context: ..
      dockerfile: src/test.Dockerfile
