services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    init: true
    volumes:
      - ../data:/usr/project/data
  test:
    build:
      context: .
      dockerfile: test.Dockerfile
