name: Build CI

on:
  push:
    branches:
      - main # Run on pushes to the main branch
  pull_request:
    branches:
      - main # Run on PRs targeting the main branch

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Prerequisites
      - name: Install Prerequisites
        run: sudo apt-get update && sudo apt-get install -y docker docker-compose

      # Build and run the tests
      - name: Run tests
        run: docker-compose -f src/docker-compose.yml build
  
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Prerequisites
      - name: Install Prerequisites
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake make

      # Build and run the tests
      - name: Run tests
        run: ./src/scripts/build.sh main
