name: CI Test with Docker Compose

on:
  push:
    branches:
      - main # Run on pushes to the main branch
  pull_request:
    branches:
      - main # Run on PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build and run Docker Compose test
      - name: Run tests using Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./src/docker-compose.yml"
          up-flags: "--build"
          services: |
            test
