name: Format CI

on:
  push:
    branches:
      - main # Run on pushes to the main branch
  pull_request:
    branches:
      - main # Run on PRs targeting the main branch

jobs:
  format-prettier:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install prettier
      - name: Install Prerequisites
        run: npm install -g prettier

      # Run formatter checks
      - name: Run formatter checks
        run: npx prettier . --check
